### ISSUE TITLE
addin no longer works on my database, server returning error after file upload

### ISSUE THREAD

**Issue by stechnique** [Geotab/addin-fuel-transaction-import#1]
Hi guys,

I am working on adding a new parser for Ultramar CSV format, but in testing on my database the add-in does not work. When I submit the file, I get an error (even with the provided example).

This is what Chrome chokes on:

    "Unexpected token < in JSON at position 0"

This is what the request looks like:

	------WebKitFormBoundaryPzJYUB8o918BgI2A
	Content-Disposition: form-data; name="fileToUpload"; filename="generic_fuel_card_csv_file_sample.csv"
	Content-Type: text/csv

	------WebKitFormBoundaryPzJYUB8o918BgI2A
	Content-Disposition: form-data; name="JSON-RPC"

	{"id":-1,"method":"ExcelToJson","params":{"minColumnsAmount":28,"credentials":{"database":"proxi_telecom","sessionId":"XXXXXXXXXXXXXXXX","userName":"XXX@XXX.XX"}}}
	------WebKitFormBoundaryPzJYUB8o918BgI2A--

And this is what the response is:

	<html>
	    <head>
	        <title>The link you used is not valid</title>
	    </head>
	    <body>
	            <span><h1>Web Error<hr width=100% size=1 color=silver></h1>
	            <h2>The link you used is not valid</h2></span>
	            <hr width=100% size=1 color=silver>
	            file content-type
	            <p>
	            MyGeotab 0.0.0.0
	    </body>
	</html>

Not sure if I should take this to the Geotab forums or here. Since I'm working on this add-in in order to issue a pull request within the next few days I thought I would try my luck. I am on my32.

**Comment by beefo** [comment]
@stechnique is this error occurring while testing locally via "gulp serve"?

**Comment by stechnique** [comment]
No in production on the database.
